### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by philipborg** [korlibs/kbignum#1]
In README.md we find
[![Maven Version](https://img.shields.io/github/tag/korlibs/kbignum.svg?style=flat&label=maven)](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22kbignum%22)
with a link that is a search which only finds a ScalaJS Library? Will you publish the library on a repository as a pom any time soon?

**Comment by philipborg** [comment]
Tagging because you are not set as watcher @soywiz

**Comment by soywiz** [comment]
It is published here: https://dl.bintray.com/soywiz/soywiz/com/soywiz/kbignum-jvm/0.9.0/

You can use `https://dl.bintray.com/soywiz/soywiz/` as maven repository

**Comment by philipborg** [comment]
@soywiz Thanks, it works 😄 
I might make some PRs sometime.
