### ISSUE TITLE
[Feature request] Support ranges

### ISSUE THREAD

**Issue by y9san9** [korlibs/kbignum#10]
Hello! This improvement should help to integrate kbignum with Kotlin.
When I have such a simple case to iterate from one bignum to another one, I should write such a function right now:
<img width="707" alt="Снимок экрана 2021-11-11 в 12 59 10" src="https://user-images.githubusercontent.com/46930374/141278185-bc3e6c2e-e9a0-4c9a-997e-572a917bcf8d.png">

**Comment by soywiz** [comment]
I think that could be a great addition indeed.
Would you mind making a PR here adding it? https://github.com/korlibs/korge-next/blob/master/kbignum/src/commonMain/kotlin/com/soywiz/kbignum/BigInt.kt

**Comment by y9san9** [comment]
Okay, I will do it as soon as I can 🙂
It shouldn't take a lot of time.
