### ISSUE TITLE
BigNum.div with precision is broken

### ISSUE THREAD

**Issue by mcekovic** [korlibs/kbignum#6]
fun div(other: BigNum, precision: Int): BigNum

is broken, it does not take into account precision parameter at all.

The implementation should be something like:

operator fun div(other: BigNum, precision: Int = other.int.significantBits / 2): BigNum {
   return BigNum(int * (10.bi pow (other.scale + precision)) / other.int, scale) * BigNum(1.bi, precision)
}

**Comment by y9san9** [comment]
This is kinda old issue, sadly :disappointed:, but I would provide a minimal reproduce for this:

Not working:
```kotlin
val bi1 = BigNum("1").convertToScale(otherScale = 10)
val bi2 = BigNum("2").convertToScale(otherScale = 10)
assertEquals(
    expected = 0.5.bn,
    actual = bi1 / bi2
)
```

Working:
```kotlin
val bi1 = BigNum("1").convertToScale(otherScale = 1)
val bi2 = BigNum("2").convertToScale(otherScale = 1)
assertEquals(
    expected = 0.5.bn,
    actual = bi1 / bi2
)
```

**Comment by soywiz** [comment]
```
assertEquals("5000000000".bi, "100000000000000000000".bi / "20000000000".bi)
```

```
expected:<5000000000> but was:<705032705>
```

It seems to be a problem with BigInt division in this case
